version: '2'

services:
  bitcoin:
    extends:
      file: docker-compose.tmpl.yml
      service: bitcoin-base-mainnet

  counterparty:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-base-mainnet
    links:
      - bitcoin
  mongodb:
    extends:
      file: docker-compose.tmpl.yml
      service: mongodb-base

  redis:
    extends:
      file: docker-compose.tmpl.yml
      service: redis-base

  armory-utxsvr:
    extends:
      file: docker-compose.tmpl.yml
      service: armory-utxsvr-base-mainnet
    links:
      - bitcoin

  counterblock:
    extends:
      file: docker-compose.tmpl.yml
      service: counterblock-base-mainnet
    links:
      - bitcoin
      - counterparty
      - mongodb
      - redis
      - armory-utxsvr

  counterwallet:
    extends:
      file: docker-compose.tmpl.yml
      service: counterwallet-base
    links:
      - redis
      - counterblock
      - counterblock-testnet

volumes:
  bitcoin-data:
  counterparty-data:
  counterblock-data:
  mongodb-data:
  armory-data:
